In [4]:
import numpy as np

zeros = np.zeros(5)
print(zeros)

[0. 0. 0. 0. 0.]


In [ ]:
value = np.zeros((3, 5, 5))  # row x column

In [22]:
value.shape

(3, 5, 5)

In [23]:
value.ndim

3

In [24]:
value.size

75

In [28]:
ones_array = np.ones(5)
print(ones_array)

[1. 1. 1. 1. 1.]


In [ ]:
np.full((3, 5), 5)  # full , ones , zeros , empty

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [ ]:
np.empty((4, 6))

array([[9.59995508e-316, 0.00000000e+000, 6.13741918e-310,
        6.13739578e-310, 6.13741918e-310, 6.13739578e-310],
       [6.13739679e-310, 6.13739578e-310, 6.13739679e-310,
        6.13739579e-310, 6.13739679e-310, 6.13739579e-310],
       [4.37927140e-317, 6.13739577e-310, 6.13741917e-310,
        6.13739577e-310, 6.13741917e-310, 6.13739577e-310],
       [4.44142091e-317, 6.13739577e-310, 6.13741918e-310,
        6.13739577e-310, 6.13741918e-310, 6.13739577e-310]])

In [50]:
# Creating an ndarray using arrange function in numpy.
# arange is a range ( similar to range in python.)

nump_array = np.arange(1, 56, 2)
nump_array

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55])

In [ ]:
np.arange(1.05, 5.0, 0.5)

array([1.05, 1.55, 2.05, 2.55, 3.05, 3.55, 4.05, 4.55])

In [ ]:
np.linspace(1, 3, 20)  # this is numerical methods .

array([1.        , 1.10526316, 1.21052632, 1.31578947, 1.42105263,
       1.52631579, 1.63157895, 1.73684211, 1.84210526, 1.94736842,
       2.05263158, 2.15789474, 2.26315789, 2.36842105, 2.47368421,
       2.57894737, 2.68421053, 2.78947368, 2.89473684, 3.        ])

In [165]:
value = np.random.default_rng(seed=34)
value

rng_pcg = np.random.Generator(np.random.PCG64DXSM())
rng_pcg.random(34)

array([0.12495943, 0.29832807, 0.55903415, 0.02783026, 0.8636627 ,
       0.75387492, 0.99515099, 0.62562646, 0.15113056, 0.23318981,
       0.16352839, 0.08548534, 0.43787405, 0.3555882 , 0.67720084,
       0.96236432, 0.04733205, 0.07516555, 0.22882931, 0.27914372,
       0.83710488, 0.90231988, 0.29251691, 0.63385243, 0.85579667,
       0.7244163 , 0.69699673, 0.8932343 , 0.67604517, 0.00663178,
       0.61788408, 0.82165937, 0.16199549, 0.83277142])