In [ ]:
# Normalization Concept.

import numpy as np
from sklearn.preprocessing import MinMaxScaler


X = np.array([[10], [20], [30], [40], [100]])
print(X)
scalar = MinMaxScaler(feature_range=(0, 1))
X_transform = scalar.fit_transform(X)
print(X_transform)

[[ 10]
 [ 20]
 [ 30]
 [ 40]
 [100]]
[[0.        ]
 [0.11111111]
 [0.22222222]
 [0.33333333]
 [1.        ]]


In [ ]:
# Z score normalization.

from sklearn.preprocessing import StandardScaler

X = np.array([[10], [20], [30], [40], [100]])
scalarr = StandardScaler()
x_transformed = scalarr.fit_transform(X)
print(x_transformed)

[[-0.9486833 ]
 [-0.63245553]
 [-0.31622777]
 [ 0.        ]
 [ 1.8973666 ]]


In [31]:
# Normalization by decimal scaling.

X = np.array([[10], [20], [30], [40], [100], [200], [454]])

j = len(str(np.max(np.abs(X))))
x_transformedd = X / 10**j


print(x_transformedd)

[[0.01 ]
 [0.02 ]
 [0.03 ]
 [0.04 ]
 [0.1  ]
 [0.2  ]
 [0.454]]


In [34]:
# Feature endoding.

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
cities = ["Kathmandu", "Pokhara", "Biratnagar"]
encoded = le.fit_transform(cities)
print(encoded)

[1 2 0]


In [ ]:
# One hot encoding.
import pandas as pd


df = pd.DataFrame({"source": ["river", "lake", "well"]})

df_encoded = pd.get_dummies(df, columns=["source"])
print(df_encoded)

   source_lake  source_river  source_well
0        False          True        False
1         True         False        False
2        False         False         True


In [44]:
# One hot encoding using sklearn
from sklearn.preprocessing import OneHotEncoder

oee = OneHotEncoder()
objD = [["male"], ["female"], ["male"], ["female"]]
encoded_onehot = oee.fit_transform(objD)
print(encoded_onehot)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4 stored elements and shape (4, 2)>
  Coords	Values
  (0, 1)	1.0
  (1, 0)	1.0
  (2, 1)	1.0
  (3, 0)	1.0


In [42]:
# Ordinal encoding


from sklearn.preprocessing import OrdinalEncoder


encoder = OrdinalEncoder(categories=[["poor", "fair", "good"]])
quality = [['poor'],['good'],['fair']]
encoded = encoder.fit_transform(quality)
print(encoded)

[[0.]
 [2.]
 [1.]]
